export const DATA_LOADING = "DATA_LOADING";
export type DATA_LOADING = "DATA_LOADING";

export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export type FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";

export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";
export type FETCH_DATA_ERROR = "FETCH_DATA_ERROR";

export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS";
export type ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS";
